config/routes.rb
WsRails::Application.routes.draw do
  resources :orders

  get 'mybills' => 'my_bills#index'

  resources :restaurants do
    resources :dishes
  end

  resources :groups do
    resources :orders
  end

  namespace :api do
    namespace :v1 do
      post "users", :to => "registrations#create"
      devise_for :users
      get 'restaurants' => 'restaurants#list'
      get 'groups/:id/dishes' => 'dishes#detail'
      get 'groups/active' => 'groups#active'
      get 'groups/:id' => 'groups#detail'
      get 'groups/:id/due_date' => 'groups#due_date'
      post 'groups/create' => 'groups#create'
      post 'groups/:group_id/orders/create' => 'orders#create'
      get 'mybills' => 'orders#list'
      get 'mybills/paid/:id' => 'orders#paid'
      get 'orders/delete/:id' => 'orders#delete'
      resources :groups
    end
  end

  authenticated :user do
    root :to => redirect("/groups")
  end

  root :to => redirect("/users/sign_in")

  devise_for :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  has_many :orders
  attr_accessible :id, :user, :restaurant, :description, :due_date, :name

  validates_presence_of :user, :restaurant, :due_date


end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < Api::V1::BaseController
  before_filter

  def active
    @active_groups = Group.where('due_date >= ?', Date.current).order("due_date DESC")
    render :file => 'rabl/active_groups'
  end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    @group = Group.create(:user => current_user, :restaurant => restaurant, :name => params[:name], :due_date => Time.parse(params[:due_date]))
    if @group.valid?
      #UserMailer.send.deliver
      render :file => 'rabl/group'
    else
      respond_with(@group)
    end
  end

  def due_date
    @group = Group.find(params[:id])
    render :file => 'rabl/due_date'
  end

  def detail
    @group = Group.find(params[:id])
    render :file => 'rabl/detail'
  end
end

app/controllers/groups_controller.rb
class   GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new

    @group = Group.new
    @restaurant = Restaurant.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  #def edit
  #  @group = Group.find(params[:id])
  #end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    #@dishes = Dish.new(@group.restaurant)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end


  def edit
    @group = Group.find(params[:id])
    @dishes = @group.restaurant.dishes
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.association :user
    = f.input :due_date
    = f.association :restaurant

  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
!!!
%html
  %head
    %title My Page
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no", :name => "viewport"}
    = stylesheet_link_tag "themes/default/all", :media => "all"
  %body
    .loading
    #group-list{"data-role" => "page"}
      %div{"data-role" => "header"}
        %a.ui-btn-left.log-out{"data-theme" => "c", :href => "javascript:void(0);"} 登出
        %h1 饭团列表
        %a.ui-btn-right.my-bills{"data-icon" => "arrow-r","data-theme" => "c", :href => "javascript:void(0);"} 我的账单
      %div{"data-role" => "content"}
        %a.create-group{"data-role" => "button", :href => "javascript:void(0);"}创建饭团
        %h2 与我相关的饭团
        %ul.my-orders-ul{"data-inset" => "true", "data-role" => "listview"}
        %h2 可参加的饭团们
        %ul.group-list-ul{"data-inset" => "true", "data-role" => "listview"}
  = javascript_include_tag "compress/group-list-all"

app/views/groups/new.html.haml
!!!
%html
  %head
    %title My Page
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no", :name => "viewport"}
    = stylesheet_link_tag "themes/default/all", :media => "all"
  %body
    .loading
    #create-group{"data-role" => "page"}
      %div{"data-role" => "header"}
        %a.ui-btn-left{"data-icon" => "arrow-l", "data-theme" => "c", :href => "javascript:void(0);"} 返回
        %h1 创建饭团
        %a.ui-btn-right.create-group-btn{"data-theme" => "c", :href => "javascript:void(0);"} 创建
      %div{"data-role" => "content"}
        %h2 饭团名 :
        %input#group-name{:type => "text",:required => true}
        %div.radio-content-list
        %a.more-restaurants{"data-role" => "button", :href => "javascript:void(0);"} 选择其他馆子
        %h2 截止时间 :
        %ul.listview{"data-role" => "listview", "data-inset"=>"true"}
          %li
            %span#show-Time
        %div#timePicker
        %a.create-group-btn{"data-role" => "button", :href => "javascript:void(0);"} 创建
  = javascript_include_tag "compress/group-create-all"

app/views/groups/show.html.haml
!!!
%html
  %head
    %title My Page
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no", :name => "viewport"}
    = stylesheet_link_tag "themes/default/all", :media => "all"
  %body
    .loading
    #group-show{"data-role" => "page" ,"data-id" => "#{@group.id}" }
      %div{"data-role" => "header"}
        %a.ui-btn-left{"data-icon" => "arrow-l", "data-theme" => "c", :href => "#group-list"} 返回
        %h1.group-name
        %a.ui-btn-right.buy-foods{"data-icon" => "arrow-r", "data-iconpos" => "right", "data-id" => "#{@group.id}", "data-theme" => "c", :href => "javascript:void(0);"} 去点餐
      %div.info-details{"data-role" => "content"}
        %div.details-content.group-details
          %h2 本团介绍
          %ul.listview.current-group-details{"data-role" => "listview", "data-inset"=>"true"}

          %h2 餐馆简介
          %ul.listview.restaurant-details{"data-role" => "listview", "data-inset"=>"true"}

        %div.details-content.my-orders-details
          %h2 我的订餐
          %ul.listview.order-status{"data-role" => "listview", "data-inset"=>"true"}
            -#%li
            -#  %h2 王锐
            -#  %table
            -#    %tr
            -#      %td.dish-name 蒙面
            -#      %td.dish-price 12$
            -#      %td.dish-count
            -#        %div.dish-count
            -#          %span.ui-li-count 1
            -#    %tr
            -#      %td.dish-name 总计
            -#      %td.dish-price 24$
            -#      %td

        %div.details-content.all-status
          %h2 统计信息
          %ul.listview.order-status{"data-role" => "listview", "data-inset"=>"true"}
            -#%li
            -#  %table
            -#    %tr
            -#      %td.dish-name 小炒肉
            -#      %td.dish-price 12$
            -#      %td.dish-count
            -#        %div.dish-count
            -#          %span.ui-li-count 4
            -#    %tr
            -#      %td.dish-name 总计
            -#      %td.dish-price 245$
            -#      %td

        %div.details-content.members-details
          %h2 团员订餐信息
          %ul.listview.order-status{"data-role" => "listview", "data-inset"=>"true"}
            -#%li
            -#  %h2 明星
            -#  %table
            -#    %tr
            -#      %td.dish-name 小炒肉
            -#      %td.dish-price 12$
            -#      %td.dish-count
            -#        %div.dish-count
            -#          %span.ui-li-count 1
            -#    %tr
            -#      %td.dish-name 总计
            -#      %td.dish-price 12$
            -#      %td
            -#%li

        -#%a.buy-foods{ :href => "javascript:void(0);" ,"data-role" => "button"} 买饭去

      %div.fixed-footer{"data-position" => "fixed", "data-role" => "footer"}
        %div{"data-role" => "navbar"}
          %ul
            %li
              %a.restaurant-info-btn{:href => "","data-icon"=>"star","data-iconpos"=>"top"} 本团信息
            %li
              %a.all-info-btn{:href => "","data-icon"=>"star","data-iconpos"=>"top"} 统计信息
            %li
              %a.my-orders-btn{:href => "","data-icon"=>"star","data-iconpos"=>"top"} 我的订餐
            %li
              %a.members-orders-btn{:href => "","data-icon"=>"star","data-iconpos"=>"top"} 团员信息


  = javascript_include_tag "compress/group-show-all"