config/routes.rb
WsRails::Application.routes.draw do
  resources :orders

  get 'mybills' => 'my_bills#index'

  resources :restaurants do
    resources :dishes
  end

  resources :groups do
    resources :orders
  end

  namespace :api do
    namespace :v1 do
      post "users", :to => "registrations#create"
      devise_for :users
      get 'restaurants' => 'restaurants#list'
      get 'groups/:id/dishes' => 'dishes#detail'
      get 'groups/active' => 'groups#active'
      get 'groups/:id' => 'groups#detail'
      get 'groups/:id/due_date' => 'groups#due_date'
      post 'groups/create' => 'groups#create'
      post 'groups/:group_id/orders/create' => 'orders#create'
      get 'mybills' => 'orders#list'
      get 'mybills/paid/:id' => 'orders#paid'
      get 'orders/delete/:id' => 'orders#delete'
      resources :groups
    end
  end

  authenticated :user do
    root :to => redirect("/groups")
  end

  root :to => redirect("/users/sign_in")

  devise_for :users

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :cuisine
  attr_accessible :id, :description, :image_url, :name, :price, :restaurant, :cuisine
end

app/controllers/api/v1/dishes_controller.rb
class Api::V1::DishesController < Api::V1::BaseController
  before_filter

  def detail
    @group = Group.find(params[:id])
    @restaurant = @group.restaurant
    @cuisines = @restaurant.cuisines

    render :file => 'rabl/cuisines'
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_filter :find_restaurant

  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to [@restaurant, @dish], notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to [@restaurant, @dish], notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to restaurant_dishes_url(@restaurant) }
      format.json { head :no_content }
    end
  end

  private
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.haml
= simple_form_for [@restaurant, @dish] do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :price
    = f.input :description
    = f.input :image_url
    = f.association :restaurant

  .form-actions
    = f.button :submit

app/views/dishes/edit.html.haml
%h1 Editing dish

= render 'form'

= link_to 'Show', restaurant_dish_path(@restaurant, @dish)
\|
= link_to 'Back', restaurant_dishes_path

app/views/dishes/index.html.haml
%h1 Listing dishes

%table
  %tr
    %th Name
    %th Price
    %th Description
    %th Image url
    %th Restaurant
    %th
    %th
    %th

  - @dishes.each do |dish|
    %tr
      %td= dish.name
      %td= dish.price
      %td= dish.description
      %td= dish.image_url
      %td= dish.restaurant
      %td= link_to 'Show', restaurant_dish_path(@restaurant, dish)
      %td= link_to 'Edit', edit_restaurant_dish_path(@restaurant, dish)
      %td= link_to 'Destroy', [@restaurant, dish], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Dish', new_restaurant_dish_path(@restaurant)

app/views/dishes/new.html.haml
%h1 New dish

= render 'form'

= link_to 'Back', restaurant_dishes_path(@restaurant)

app/views/dishes/show.html.haml
%p
  %b Name:
  = @dish.name
%p
  %b Price:
  = @dish.price
%p
  %b Description:
  = @dish.description
%p
  %b Image url:
  = @dish.image_url
%p
  %b Restaurant:
  = @dish.restaurant

= link_to 'Edit', edit_restaurant_dish_path(@restaurant, @dish)
\|
= link_to 'Back', restaurant_dishes_path(@restaurant)