config/routes.rb
WsRails::Application.routes.draw do
  resources :orders

  get 'mybills' => 'my_bills#index'

  resources :restaurants do
    resources :dishes
  end

  resources :groups do
    resources :orders
  end

  namespace :api do
    namespace :v1 do
      post "users", :to => "registrations#create"
      devise_for :users
      get 'restaurants' => 'restaurants#list'
      get 'groups/:id/dishes' => 'dishes#detail'
      get 'groups/active' => 'groups#active'
      get 'groups/:id' => 'groups#detail'
      get 'groups/:id/due_date' => 'groups#due_date'
      post 'groups/create' => 'groups#create'
      post 'groups/:group_id/orders/create' => 'orders#create'
      get 'mybills' => 'orders#list'
      get 'mybills/paid/:id' => 'orders#paid'
      get 'orders/delete/:id' => 'orders#delete'
      resources :groups
    end
  end

  authenticated :user do
    root :to => redirect("/groups")
  end

  root :to => redirect("/users/sign_in")

  devise_for :users

end

app/models/Restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :cuisines
  attr_accessible :name, :telephone, :address, :image_url, :note
end

app/controllers/api/v1/restaurants_controller.rb
class Api::V1::RestaurantsController < Api::V1::BaseController
  def list
    @restaurants = Restaurant.all
    render :file => 'rabl/restaurants'
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurant = Restaurant.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurant }
    end
  end

  def list
    @restaurant = Restaurant.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
= simple_form_for(@restaurant) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :telephone
    = f.input :address
    = f.input :image_url

  .form-actions
    = f.button :submit

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
!!!
%html
  %head
    %title My Page
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag "themes/default/all", :media => "all"
  %body
    #restaurants-list{"data-role" => "page"}
      %div{"data-role" => "header"}
        %a.ui-btn-left{"data-icon" => "arrow-l", "data-theme" => "c", :href => "javascript:void(0);"} 返回
        %h1 饭馆们
      %div.details-content{"data-role" => "content"}
        %ul.restaurant-list-content{"data-filter" => "true", "data-filter-placeholder" => "Search restaurant...", "data-inset" => "true", "data-role" => "listview"}
          - @restaurant.each do |item|
            %li{"data-icon"=>"check"}
              %a{"data-id"=>"#{item.id}", :href => "javascript:void(0);"}= item.name

  = javascript_include_tag "compress/restaurant-list-all"

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @restaurant.name
%p
  %b Telephone:
  = @restaurant.telephone
%p
  %b Address:
  = @restaurant.address
%p
  %b Image url:
  = @restaurant.image_url

= link_to 'Edit', edit_restaurant_path(@restaurant)
\|
= link_to 'Back', restaurants_path